fix(fff): test9-1 doesn't work (BASE-1111)

diff --git a/.github/workflows/check-commit-message-push.yaml b/.github/workflows/check-commit-message-push.yaml
--- a/.github/workflows/check-commit-message-push.yaml
+++ b/.github/workflows/check-commit-message-push.yaml
@@ -15,10 +15,10 @@ jobs:
         run: |
           # shellcheck source=/dev/null
           source ".env.commit_message_regexp"
-          set -o errexit   # exit on error
-          set -o nounset   # fail if var undefined
-          set -o noclobber # don't overwrite exists files via >
-          set -o pipefail  # fails if pipes (|) fails
+          #set -o errexit   # exit on error
+          #set -o nounset   # fail if var undefined
+          #set -o noclobber # don't overwrite exists files via >
+          #set -o pipefail  # fails if pipes (|) fails
           set -o xtrace  # debug
           readarray -t LIST_MESSAGE_COMMITS < <(echo '${{ toJSON(github.event.commits) }}' | jq -r ".[].message")
           if ! [[ "${LIST_MESSAGE_COMMITS[0]}" =~ ${COMMIT_MESSAGE_REGEXP} ]]; then
