fix(fff): test11-6 doesn`t work (BASE-1111)

diff --git a/.github/workflows/check-commit-message-push.yaml b/.github/workflows/check-commit-message-push.yaml
--- a/.github/workflows/check-commit-message-push.yaml
+++ b/.github/workflows/check-commit-message-push.yaml
@@ -13,5 +13,9 @@ jobs:
         uses: actions/checkout@v3
       - name: Check message commits on push
         run: |
-          echo '${{ github.event.commits[0].message }}'
+          if ! [[ '${{ github.event.commits[0].message }}' =~ ${COMMIT_MESSAGE_REGEXP} ]]; then
+            echo "Invalid message commit:"
+            echo '${{ github.event.commits[0].message }}'
+            exit 1
+          fi
         shell: bash {0}
