feat(php): ggggg (XXXX-1485)   - ghhhh/jjjjj (v1.25.0 => v1.26.0): Extracting archive

diff --git a/.github/workflows/check-commit-message-push.yaml b/.github/workflows/check-commit-message-push.yaml
--- a/.github/workflows/check-commit-message-push.yaml
+++ b/.github/workflows/check-commit-message-push.yaml
@@ -21,13 +21,17 @@ jobs:
           set -o pipefail  # fails if pipes (|) fails
           # set -o xtrace  # debug
           readarray -t LIST_MESSAGE_COMMITS < <(echo '${{ toJSON(github.event.commits) }}' | jq -r ".[].message")
+          ERROR_FOUND=0
           for MESSAGE_COMMIT in "${LIST_MESSAGE_COMMITS[@]}"
           do
             if ! [[ "${MESSAGE_COMMIT}" =~ ${COMMIT_MESSAGE_REGEXP} ]]; then
-              echo "Invalid message commit:"
+              echo "Invalid message commit, regexp : ${COMMIT_MESSAGE_REGEXP}"
               echo "${MESSAGE_COMMIT}"
-              exit 1
+              ERROR_FOUND=1
             fi
           done
+          if [ $ERROR_FOUND -eq 1 ]; then
+            exit 1
+          fi
 
         shell: bash {0}
