feat(php): update php packages (BASE-1485)   - Upgrading symfony/polyfill-php80 (v1.25.0 => v1.26.0): Extracting archive   - Upgrading symfony/polyfill-mbstring (v1.25.0 => v1.26.0): Extracting archive   - Upgrading symfony/polyfill-ctype (v1.25.0 => v1.26.0): Extracting archive   - Upgrading symfony/var-dumper (v5.4.6 => v5.4.9): Extracting archive

diff --git a/.github/workflows/check-commit-message-push.yaml b/.github/workflows/check-commit-message-push.yaml
--- a/.github/workflows/check-commit-message-push.yaml
+++ b/.github/workflows/check-commit-message-push.yaml
@@ -11,24 +11,27 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-      - name: Check message commits on push by script
-        uses: actions/github-script@v6
-        with:
-          script: |
-            const commits = ${{ toJSON(github.event.commits) }}
-            var ERROR_FOUND=0;
-            for (const commit of commits) {
-              const {COMMIT_MESSAGE_REGEXP} = require(".env.commit_message_regexp");
-              var firstline = commit.message.trim().split("\n")[0]
-              if(firstline.match(COMMIT_MESSAGE_REGEXP)){
-                console.log("message commit match regex: " + COMMIT_MESSAGE_REGEXP);
-              } else {
-                console.log("message commit does not match regex: " + COMMIT_MESSAGE_REGEXP);
-                console.log(firstline);
-                ERROR_FOUND=1;
-              }
-            }
-            console.log(ERROR_FOUND);
-            if(ERROR_FOUND == 1){
-              core.setFailed("Have invalid message commit");
-            }
+      - name: Check message commits on push
+        run: |
+          # shellcheck source=/dev/null
+          source ".env.commit_message_regexp"
+          set -o errexit   # exit on error
+          set -o nounset   # fail if var undefined
+          set -o noclobber # don't overwrite exists files via >
+          set -o pipefail  # fails if pipes (|) fails
+          # set -o xtrace  # debug
+          readarray -t LIST_MESSAGE_COMMITS < <(echo '${{ toJSON(github.event.commits) }}' | jq ".[].message")
+          ERROR_FOUND=0
+          for MESSAGE_COMMIT in "${LIST_MESSAGE_COMMITS[@]}"
+          do
+            if ! [[ "${MESSAGE_COMMIT:1:-1}" =~ ${COMMIT_MESSAGE_REGEXP} ]]; then
+              echo "Invalid message commit, regexp : ${COMMIT_MESSAGE_REGEXP}"
+              echo "${MESSAGE_COMMIT}"
+              ERROR_FOUND=1
+            fi
+          done
+          if [ $ERROR_FOUND -eq 1 ]; then
+            exit 1
+          fi
+
+        shell: bash {0}
