fix(fff): test11-6 doesn`t work (BASE-1111)

diff --git a/.github/workflows/check-commit-message-push.yaml b/.github/workflows/check-commit-message-push.yaml
--- a/.github/workflows/check-commit-message-push.yaml
+++ b/.github/workflows/check-commit-message-push.yaml
@@ -13,6 +13,13 @@ jobs:
         uses: actions/checkout@v3
       - name: Check message commits on push
         run: |
+          # shellcheck source=/dev/null
+          source ".env.commit_message_regexp"
+          set -o errexit   # exit on error
+          set -o nounset   # fail if var undefined
+          set -o noclobber # don't overwrite exists files via >
+          set -o pipefail  # fails if pipes (|) fails
+          # set -o xtrace  # debug
           if ! [[ '${{ github.event.commits[0].message }}' =~ ${COMMIT_MESSAGE_REGEXP} ]]; then
             echo "Invalid message commit:"
             echo '${{ github.event.commits[0].message }}'
