fix(fff): test11-15 doesn`t work (BASE-1111)

diff --git a/.github/workflows/check-commit-message-push.yaml b/.github/workflows/check-commit-message-push.yaml
--- a/.github/workflows/check-commit-message-push.yaml
+++ b/.github/workflows/check-commit-message-push.yaml
@@ -21,9 +21,13 @@ jobs:
           set -o pipefail  # fails if pipes (|) fails
           # set -o xtrace  # debug
           readarray -t LIST_MESSAGE_COMMITS < <(echo '${{ toJSON(github.event.commits) }}' | jq -r ".[].message")
-          if ! [[ ${LIST_MESSAGE_COMMITS[0]} =~ ${COMMIT_MESSAGE_REGEXP} ]]; then
-            echo "Invalid message commit:"
-            echo "${LIST_MESSAGE_COMMITS[0]}"
-            exit 1
-          fi
+          for MESSAGE_COMMIT in "${LIST_MESSAGE_COMMITS[@]}"
+          do
+            if ! [[ "${MESSAGE_COMMIT}" =~ ${COMMIT_MESSAGE_REGEXP} ]]; then
+              echo "Invalid message commit:"
+              echo "${MESSAGE_COMMIT}"
+              exit 1
+            fi
+          done
+
         shell: bash {0}
